export enum StorageCategory {
  PROJECT_FILE = 'project_file',
  TASK_FILE = 'task_file',
  CONTRACT = 'contract',
  PROPOSAL = 'proposal',
  RECEIPT = 'receipt',
  DELIVERABLE = 'deliverable',
  INTAKE_FORM = 'intake_form',
  CHAT_ATTACHMENT = 'chat_attachment',
}

export const STORAGE_CONFIG: Record<
  StorageCategory,
  {
    keyPrefix: string;
    maxFileSize: number;
    allowedMimeTypes: string[];
  }
> = {
  [StorageCategory.PROJECT_FILE]: {
    keyPrefix: 'projects',
    maxFileSize: 50 * 1024 * 1024,
    allowedMimeTypes: [
      'image/png',
      'image/jpeg',
      'image/gif',
      'image/webp',
      'image/svg+xml',
      'application/pdf',
      'application/msword',
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      'application/vnd.ms-excel',
      'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      'application/vnd.ms-powerpoint',
      'application/vnd.openxmlformats-officedocument.presentationml.presentation',
      'application/zip',
      'application/x-rar-compressed',
      'application/x-7z-compressed',
      'text/plain',
      'text/csv',
    ],
  },
  [StorageCategory.TASK_FILE]: {
    keyPrefix: 'tasks',
    maxFileSize: 100 * 1024 * 1024,
    allowedMimeTypes: [
      'image/png',
      'image/jpeg',
      'image/gif',
      'image/webp',
      'image/svg+xml',
      'application/pdf',
      'application/msword',
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      'application/vnd.ms-excel',
      'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      'application/vnd.ms-powerpoint',
      'application/vnd.openxmlformats-officedocument.presentationml.presentation',
      'application/zip',
      'application/x-rar-compressed',
      'application/x-7z-compressed',
      'text/plain',
      'text/csv',
      'video/mp4',
      'video/quicktime',
      'video/webm',
    ],
  },
  [StorageCategory.CONTRACT]: {
    keyPrefix: 'contracts',
    maxFileSize: 50 * 1024 * 1024,
    allowedMimeTypes: ['application/pdf'],
  },
  [StorageCategory.PROPOSAL]: {
    keyPrefix: 'proposals',
    maxFileSize: 50 * 1024 * 1024,
    allowedMimeTypes: ['application/pdf'],
  },
  [StorageCategory.RECEIPT]: {
    keyPrefix: 'payments',
    maxFileSize: 20 * 1024 * 1024,
    allowedMimeTypes: [
      'image/png',
      'image/jpeg',
      'image/gif',
      'image/webp',
      'application/pdf',
    ],
  },
  [StorageCategory.DELIVERABLE]: {
    keyPrefix: 'deliverables',
    maxFileSize: 100 * 1024 * 1024,
    allowedMimeTypes: [
      'image/png',
      'image/jpeg',
      'image/gif',
      'image/webp',
      'image/svg+xml',
      'application/pdf',
      'application/msword',
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      'application/vnd.ms-excel',
      'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      'application/vnd.ms-powerpoint',
      'application/vnd.openxmlformats-officedocument.presentationml.presentation',
      'application/zip',
      'text/plain',
      'text/csv',
      'video/mp4',
      'video/quicktime',
      'video/webm',
    ],
  },
  [StorageCategory.INTAKE_FORM]: {
    keyPrefix: 'intake-forms',
    maxFileSize: 50 * 1024 * 1024,
    allowedMimeTypes: [
      'image/png',
      'image/jpeg',
      'image/gif',
      'image/webp',
      'application/pdf',
      'application/msword',
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      'text/plain',
    ],
  },
  [StorageCategory.CHAT_ATTACHMENT]: {
    keyPrefix: 'chat',
    maxFileSize: 25 * 1024 * 1024,
    allowedMimeTypes: [
      'image/png',
      'image/jpeg',
      'image/gif',
      'image/webp',
      'image/svg+xml',
      'application/pdf',
      'application/msword',
      'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
      'application/zip',
      'text/plain',
      'text/csv',
      'video/mp4',
      'video/quicktime',
      'video/webm',
    ],
  },
};

export const PRESIGNED_URL_EXPIRY_SECONDS = {
  DOWNLOAD: 3600,
  UPLOAD: 300,
} as const;

export const EXTENSION_MIME_MAP: Record<string, string> = {
  '.pdf': 'application/pdf',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.gif': 'image/gif',
  '.webp': 'image/webp',
  '.svg': 'image/svg+xml',
  '.doc': 'application/msword',
  '.docx': 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  '.xls': 'application/vnd.ms-excel',
  '.xlsx': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
  '.ppt': 'application/vnd.ms-powerpoint',
  '.pptx': 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
  '.zip': 'application/zip',
  '.rar': 'application/x-rar-compressed',
  '.7z': 'application/x-7z-compressed',
  '.txt': 'text/plain',
  '.csv': 'text/csv',
  '.mp4': 'video/mp4',
  '.mov': 'video/quicktime',
  '.webm': 'video/webm',
};