"use client";

import Link from "next/link";
import { useState } from "react";
import { ArrowLeftIcon, PauseIcon, PlayIcon, RefreshCwIcon, SquareIcon } from "lucide-react";
import { PageScaffold } from "@/components/patterns/page-scaffold";
import { StatusBadge } from "@/components/patterns/status-badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Field, FieldGroup, FieldLabel } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { showApiErrorToast, showCrmActionToast } from "@/lib/api/crm-action-toast";
import { useAddMarketingCampaignKpiMutation, useChangeMarketingCampaignStatusMutation, useFlagMarketingOptimizationMutation } from "@/lib/api/marketing-workspace-api";
import type { MarketingCampaign } from "@/lib/api/marketing-workspace-api";
import { formatCampaignPlatform, formatCampaignStatus, getCampaignStatusTone } from "@/features/marketing/lib/marketing-status";

export function MarketingCampaignDetailWorkspace({ campaign }: { campaign: MarketingCampaign }) {
  const [changeStatus, changeStatusState] = useChangeMarketingCampaignStatusMutation(); const [addKpi, addKpiState] = useAddMarketingCampaignKpiMutation(); const [flag, flagState] = useFlagMarketingOptimizationMutation();
  const isMutating = changeStatusState.isLoading || addKpiState.isLoading || flagState.isLoading;
  const [metrics, setMetrics] = useState({ budgetSpent: "", impressions: "", clicks: "", conversions: "", revenue: "" });
  const act = async (action: "start" | "pause" | "stop" | "end") => { try { await changeStatus({ id: campaign.id, action }).unwrap(); showCrmActionToast({ type: "success", title: "Campaign status updated", description: "The campaign lifecycle was updated." }); } catch (error) { showApiErrorToast(error); } };
  const saveKpi = async () => { try { await addKpi({ id: campaign.id, body: Object.fromEntries(Object.entries(metrics).filter(([, value]) => value !== "").map(([key, value]) => [key, Number(value)])) }).unwrap(); showCrmActionToast({ type: "success", title: "Snapshot recorded", description: "The latest campaign metrics were saved." }); } catch (error) { showApiErrorToast(error); } };
  const toggleOptimization = async () => { try { await flag({ id: campaign.id, needsOptimization: !campaign.needsOptimization }).unwrap(); showCrmActionToast({ type: "success", title: "Optimization flag updated", description: "Campaign attention status was updated." }); } catch (error) { showApiErrorToast(error); } };
  return <PageScaffold title={campaign.name} description={`${formatCampaignPlatform(campaign.platform)} campaign performance and lifecycle.`} actions={<Button variant="outline" nativeButton={false} render={<Link href="/marketing/campaigns" />}><ArrowLeftIcon data-icon="inline-start" />Campaigns</Button>}><div className="flex flex-col gap-4"><Card><CardHeader><div className="flex flex-wrap items-start justify-between gap-3"><div><CardTitle>{campaign.name}</CardTitle><CardDescription>{campaign.project?.name ?? "No project"} · {campaign.client?.companyName ?? "No client"}</CardDescription></div><StatusBadge tone={getCampaignStatusTone(campaign.status)}>{formatCampaignStatus(campaign.status)}</StatusBadge></div></CardHeader><CardContent className="flex flex-wrap gap-2">{campaign.status === "PLANNING" ? <Button disabled={isMutating} onClick={() => void act("start")}><PlayIcon data-icon="inline-start" />Start</Button> : null}{campaign.status === "ACTIVE" ? <Button variant="outline" disabled={isMutating} onClick={() => void act("pause")}><PauseIcon data-icon="inline-start" />Pause</Button> : null}{campaign.status === "PAUSED" ? <Button disabled={isMutating} onClick={() => void act("start")}><PlayIcon data-icon="inline-start" />Resume</Button> : null}{campaign.status === "ACTIVE" || campaign.status === "PAUSED" ? <Button variant="outline" disabled={isMutating} onClick={() => void act("stop")}><SquareIcon data-icon="inline-start" />Stop</Button> : null}<Button variant="outline" disabled={isMutating} onClick={() => void toggleOptimization()}><RefreshCwIcon data-icon="inline-start" />{campaign.needsOptimization ? "Clear optimization flag" : "Flag optimization"}</Button></CardContent></Card><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["Budget", campaign.budgetTotal], ["Spend", campaign.budgetSpent], ["Impressions", campaign.analytics?.impressions ?? 0], ["ROAS", `${Number(campaign.analytics?.roas ?? 0).toFixed(2)}x`]].map(([label, value]) => <Card key={String(label)}><CardHeader><CardDescription>{label}</CardDescription><CardTitle>{String(value)}</CardTitle></CardHeader></Card>)}</section><Card><CardHeader><CardTitle>Record KPI snapshot</CardTitle><CardDescription>Metrics are calculated and stored by the API.</CardDescription></CardHeader><CardContent className="flex flex-col gap-4"><FieldGroup><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{(["budgetSpent", "impressions", "clicks", "conversions", "revenue"] as const).map((key) => <Field key={key}><FieldLabel htmlFor={`kpi-${key}`}>{key}</FieldLabel><Input id={`kpi-${key}`} type="number" min="0" value={metrics[key]} onChange={(event) => setMetrics((current) => ({ ...current, [key]: event.target.value }))} /></Field>)}</div></FieldGroup><div><Button disabled={isMutating} onClick={() => void saveKpi()}>Save snapshot</Button></div></CardContent></Card></div></PageScaffold>;
}
