export enum AiEntityType {
  LEAD = 'LEAD',
  CLIENT = 'CLIENT',
  PROJECT = 'PROJECT',
  TASK = 'TASK',

}

export enum AiAnalysisType {
  CHURN_PREDICTION = 'CHURN_PREDICTION',
  SENTIMENT_ANALYSIS = 'SENTIMENT_ANALYSIS',
  PERFORMANCE_FORECAST = 'PERFORMANCE_FORECAST',
  CONTENT_GENERATION = 'CONTENT_GENERATION',
  QUALITY_CHECK = 'QUALITY_CHECK',
}

export enum AiSuggestionType {
  STRATEGY = 'STRATEGY',
  OPTIMIZATION = 'OPTIMIZATION',
  CONTENT = 'CONTENT',
}

export enum AiSuggestionStatus {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
}
