export enum BusinessType {
  RESTAURANT = 'RESTAURANT',
  CLINIC = 'CLINIC',
  STORE = 'STORE',
  SERVICE = 'SERVICE',
  OTHER = 'OTHER',
}

export enum ClientSource {
  AD = 'AD',
  REFERRAL = 'REFERRAL',
  WEBSITE = 'WEBSITE',
  WHATSAPP = 'WHATSAPP',
  PLATFORM = 'PLATFORM',
}

export enum PipelineStage {
  NEW_LEAD = 'NEW_LEAD',
  INTRO_MESSAGE = 'INTRO_MESSAGE',
  CONTACT_ATTEMPT = 'CONTACT_ATTEMPT',
  MEETING_SCHEDULED = 'MEETING_SCHEDULED',
  MEETING_HELD = 'MEETING_HELD',
  TECHNICAL_PROPOSAL = 'TECHNICAL_PROPOSAL',
  FOLLOW_UP = 'FOLLOW_UP',
  APPROVAL = 'APPROVAL',
  CONTRACT_SIGNED = 'CONTRACT_SIGNED',
}

export enum ClientStatus {
  LEAD = 'LEAD',
  ACTIVE = 'ACTIVE',
  STOPPED = 'STOPPED',
}

export enum ContactLogType {
  CALL = 'CALL',
  WHATSAPP = 'WHATSAPP',
  MEETING = 'MEETING',
  EMAIL = 'EMAIL',
}

export enum ContactLogResult {
  NO_RESPONSE = 'NO_RESPONSE',
  RESPONDED = 'RESPONDED',
  BUSY = 'BUSY',
  WRONG_NUMBER = 'WRONG_NUMBER',
}

export enum AutomationStatus {
  PENDING = 'PENDING',
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
}

export enum ProposalStatus {
  DRAFT = 'DRAFT',
  SENT = 'SENT',
  APPROVED = 'APPROVED',
  REVISION_REQUESTED = 'REVISION_REQUESTED',
  REJECTED = 'REJECTED',
}

export enum ContractType {
  MONTHLY_RETAINER = 'MONTHLY_RETAINER',
  FIXED_PROJECT = 'FIXED_PROJECT',
  ONE_TIME_SERVICE = 'ONE_TIME_SERVICE',
}

export enum ContractStatus {
  DRAFT = 'DRAFT',
  SENT = 'SENT',
  SIGNED = 'SIGNED',
  ACTIVE = 'ACTIVE',
  EXPIRED = 'EXPIRED',
  CANCELLED = 'CANCELLED',
}

export enum RenewalAlertType {
  SIXTY_DAYS = 'SIXTY_DAYS',
  THIRTY_DAYS = 'THIRTY_DAYS',
  SEVEN_DAYS = 'SEVEN_DAYS',
}

