export enum ServiceCategory {
  BRANDING = 'BRANDING',
  WEB_DEVELOPMENT = 'WEB_DEVELOPMENT',
  SOCIAL_MEDIA = 'SOCIAL_MEDIA',
  ADVERTISING = 'ADVERTISING',
  CONTENT_CREATION = 'CONTENT_CREATION',
  PHOTOGRAPHY = 'PHOTOGRAPHY',
  VIDEO_PRODUCTION = 'VIDEO_PRODUCTION',
  SEO = 'SEO',
  OTHER = 'OTHER',
}

export enum DeliverableStatus {
  TODO = 'TODO',
  IN_PROGRESS = 'IN_PROGRESS',
  IN_REVIEW = 'IN_REVIEW',
  DONE = 'DONE',
  REVISION = 'REVISION',
}