"use client";

import { use } from "react";
import Link from "next/link";
import { ArrowLeft, Building2, CalendarDays, CircleDollarSign, FileClock, FileText, Layers3, ShieldCheck } from "lucide-react";
import { useGetAdminContractByIdQuery } from "@/features/admin/adminContractsApi";
import type { AdminContractDetail } from "@/features/admin/adminContractsApi";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Breadcrumb, BreadcrumbItem, BreadcrumbLink, BreadcrumbList, BreadcrumbPage, BreadcrumbSeparator } from "@/components/ui/breadcrumb";
import { Empty, EmptyContent, EmptyDescription, EmptyHeader, EmptyMedia, EmptyTitle } from "@/components/ui/empty";
import { Skeleton } from "@/components/ui/skeleton";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { CONTRACT_STATUS_AR } from "@hassad/shared";
import { formatCurrency, formatDateTime, formatPortalDate, formatNumber } from "@/lib/format";

function LoadingState() { return <div className="flex flex-col gap-6 p-4 sm:p-6 lg:p-8"><Card><CardHeader className="gap-4 lg:flex-row lg:items-end lg:justify-between"><div className="flex flex-col gap-2"><Skeleton className="h-4 w-28" /><Skeleton className="h-9 w-60" /><Skeleton className="h-4 w-full max-w-xl" /></div><div className="flex gap-2"><Skeleton className="h-10 w-24" /><Skeleton className="h-10 w-28" /></div></CardHeader></Card><div className="grid gap-6 lg:grid-cols-[minmax(0,1.1fr)_minmax(0,0.9fr)]"><Card><CardContent className="flex gap-4 p-6"><Skeleton className="size-20 rounded-lg" /><div className="flex flex-1 flex-col gap-3"><Skeleton className="h-7 w-48" /><Skeleton className="h-4 w-40" /><div className="flex flex-wrap gap-2"><Skeleton className="h-8 w-28" /><Skeleton className="h-8 w-32" /><Skeleton className="h-8 w-24" /></div></div></CardContent></Card><div className="grid gap-4 md:grid-cols-2">{Array.from({ length: 4 }).map((_, index) => <Card key={index}><CardContent className="flex items-start justify-between gap-4 p-5"><div className="flex flex-col gap-2"><Skeleton className="h-4 w-24" /><Skeleton className="h-7 w-20" /><Skeleton className="h-4 w-32" /></div><Skeleton className="size-10 rounded-lg" /></CardContent></Card>)}</div></div></div>; }

function field(label: string, value?: string | number | null) { return <div className="rounded-lg border p-4"><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 text-sm font-medium">{value ?? "—"}</p></div>; }

export default function ContractDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params);
  const { data: contract, isLoading, isError } = useGetAdminContractByIdQuery(id);
  if (isLoading) return <LoadingState />;
  if (isError || !contract) return <div dir="rtl" className="p-4 sm:p-6 lg:p-8"><Card><CardContent className="p-8"><Empty><EmptyMedia variant="icon"><FileClock /></EmptyMedia><EmptyHeader><EmptyTitle>العقد غير موجود</EmptyTitle><EmptyDescription>لم نتمكن من العثور على بيانات هذا العقد.</EmptyDescription></EmptyHeader><EmptyContent><Button asChild><Link href="/dashboard/admin/contracts"><ArrowLeft />العودة إلى العقود</Link></Button></EmptyContent></Empty></CardContent></Card></div>;

  return (
    <div dir="rtl" className="flex flex-col gap-6 p-4 sm:p-6 lg:p-8">
      <Card><CardHeader className="gap-4 lg:flex-row lg:items-end lg:justify-between"><div className="flex flex-col gap-3"><Breadcrumb><BreadcrumbList><BreadcrumbItem><BreadcrumbLink asChild><Link href="/dashboard">الرئيسية</Link></BreadcrumbLink></BreadcrumbItem><BreadcrumbSeparator /><BreadcrumbItem><BreadcrumbLink asChild><Link href="/dashboard/admin/contracts">العقود</Link></BreadcrumbLink></BreadcrumbItem><BreadcrumbSeparator /><BreadcrumbItem><BreadcrumbPage>{contract.title}</BreadcrumbPage></BreadcrumbItem></BreadcrumbList></Breadcrumb><div className="flex items-center gap-3"><div className="flex size-10 items-center justify-center rounded-lg bg-primary/10 text-primary"><FileClock /></div><div className="flex flex-col gap-1"><CardTitle className="text-2xl">تفاصيل العقد</CardTitle><CardDescription>ملخص إداري ومالي مع السجل والنسخ والفواتير.</CardDescription></div></div></div><div className="flex flex-wrap gap-2"><Button variant="outline" size="sm" asChild><Link href="/dashboard/admin/contracts"><ArrowLeft />العودة</Link></Button><Button variant="outline" size="sm" asChild><Link href={`/dashboard/admin/clients/${contract.clientId}`}><Building2 />العميل</Link></Button></div></CardHeader></Card>

      <div className="grid gap-6 lg:grid-cols-[minmax(0,1.1fr)_minmax(0,0.9fr)]">
        <Card><CardContent className="flex flex-col gap-5 p-6 md:flex-row md:items-start"><div className="flex size-20 items-center justify-center rounded-lg bg-muted text-muted-foreground"><FileText className="size-10" /></div><div className="flex min-w-0 flex-1 flex-col gap-3"><div className="flex flex-wrap items-center gap-2"><h2 className="text-2xl font-semibold tracking-tight">{contract.title}</h2><Badge variant="outline">{CONTRACT_STATUS_AR[contract.status as keyof typeof CONTRACT_STATUS_AR] || contract.status}</Badge></div><p className="text-sm text-muted-foreground">{contract.client.companyName}</p><div className="flex flex-wrap gap-2"><Badge variant="outline">النسخة {formatNumber(contract.versionNumber)}</Badge><Badge variant="outline">توقيع إلكتروني {contract.eSigned ? "نعم" : "لا"}</Badge><Badge variant="outline">مرجع الطلب {contract.requestId || "—"}</Badge></div></div></CardContent></Card>
        <div className="grid gap-4 md:grid-cols-2">{[{label:"إجمالي القيمة",value:formatCurrency(contract.totalValue),icon:CircleDollarSign},{label:"القيمة الشهرية",value:formatCurrency(contract.monthlyValue),icon:CalendarDays},{label:"الفواتير",value:formatNumber(contract.invoices.length),icon:Layers3},{label:"النسخ",value:formatNumber(contract.versions.length),icon:ShieldCheck}].map((item)=><Card key={item.label}><CardContent className="flex items-start justify-between gap-4 p-5"><div className="flex flex-col gap-2"><span className="text-sm text-muted-foreground">{item.label}</span><span className="text-lg font-semibold">{item.value}</span></div><div className="flex size-10 items-center justify-center rounded-lg bg-muted text-muted-foreground"><item.icon /></div></CardContent></Card>)}</div>
      </div>

      <div className="grid gap-6 xl:grid-cols-[minmax(0,1.2fr)_minmax(0,0.8fr)]">
        <Card><CardHeader className="gap-2"><CardTitle>البيانات الأساسية</CardTitle><CardDescription>المرجع المالي والمجالي للعقد.</CardDescription></CardHeader><CardContent className="grid gap-4 md:grid-cols-2">{field("العميل", contract.client.companyName)}{field("المعرف الداخلي", contract.id)}{field("تاريخ البداية", formatPortalDate(contract.startDate) || "—")}{field("تاريخ النهاية", formatPortalDate(contract.endDate) || "—")}{field("تاريخ التوقيع", formatPortalDate(contract.signedAt) || "—")}{field("تاريخ الإنشاء", formatDateTime(contract.createdAt))}{field("المشروع", contract.project?.name || "—")}{field("إصدار الملف", formatNumber(contract.versionNumber))}</CardContent></Card>
        <Card><CardHeader className="gap-2"><CardTitle>المستندات والربط</CardTitle><CardDescription>مستند العقد، المشروع، والعرض المرتبط.</CardDescription></CardHeader><CardContent className="grid gap-4 md:grid-cols-2">{field("النوع", contract.type)}{field("العملة", contract.currency)}{field("الرابط", contract.shareLinkToken || "—")}{field("مرجع العرض", contract.proposalId || "—")}{field("الدفعة المقدمة", contract.downPaymentValue == null ? "—" : formatCurrency(contract.downPaymentValue))}{field("عدد الأشهر", formatNumber(contract.numberOfMonths))}</CardContent></Card>
      </div>

      <Card><CardHeader className="gap-2"><CardTitle>الفواتير</CardTitle><CardDescription>حالة التحصيل لكل فاتورة مرتبطة.</CardDescription></CardHeader><CardContent className="overflow-hidden rounded-lg border"><Table><TableHeader><TableRow><TableHead>الفاتورة</TableHead><TableHead>القيمة</TableHead><TableHead>الحالة</TableHead><TableHead>الاستحقاق</TableHead><TableHead>المدفوع</TableHead></TableRow></TableHeader><TableBody>{contract.invoices.length===0?<TableRow><TableCell colSpan={5} className="text-center text-muted-foreground">لا توجد فواتير</TableCell></TableRow>:contract.invoices.map((invoice)=><TableRow key={invoice.id}><TableCell>{invoice.invoiceNumber}</TableCell><TableCell>{formatCurrency(invoice.amount)}</TableCell><TableCell>{invoice.status}</TableCell><TableCell>{formatPortalDate(invoice.dueDate) || "—"}</TableCell><TableCell>{formatPortalDate(invoice.paidAt) || "—"}</TableCell></TableRow>)}</TableBody></Table></CardContent></Card>

      <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_minmax(0,1fr)]">
        <Card><CardHeader className="gap-2"><CardTitle>تاريخ الحالات</CardTitle><CardDescription>سجل الانتقال بين حالات العقد.</CardDescription></CardHeader><CardContent className="overflow-hidden rounded-lg border"><Table><TableHeader><TableRow><TableHead>من</TableHead><TableHead>إلى</TableHead><TableHead>بواسطة</TableHead><TableHead>التاريخ</TableHead></TableRow></TableHeader><TableBody>{contract.statusHistory.length===0?<TableRow><TableCell colSpan={4} className="text-center text-muted-foreground">لا يوجد سجل</TableCell></TableRow>:contract.statusHistory.map((entry)=><TableRow key={entry.id}><TableCell>{entry.fromStatus || "—"}</TableCell><TableCell>{entry.toStatus}</TableCell><TableCell>{entry.changer.name}</TableCell><TableCell>{formatDateTime(entry.changedAt)}</TableCell></TableRow>)}</TableBody></Table></CardContent></Card>
        <Card><CardHeader className="gap-2"><CardTitle>الإصدارات</CardTitle><CardDescription>نسخ العقد المحفوظة في النظام.</CardDescription></CardHeader><CardContent className="overflow-hidden rounded-lg border"><Table><TableHeader><TableRow><TableHead>الإصدار</TableHead><TableHead>الملف</TableHead><TableHead>التاريخ</TableHead></TableRow></TableHeader><TableBody>{contract.versions.length===0?<TableRow><TableCell colSpan={3} className="text-center text-muted-foreground">لا توجد نسخ</TableCell></TableRow>:contract.versions.map((version)=><TableRow key={version.id}><TableCell>{version.versionNumber}</TableCell><TableCell>{version.filePath || "—"}</TableCell><TableCell>{formatDateTime(version.createdAt)}</TableCell></TableRow>)}</TableBody></Table></CardContent></Card>
      </div>
    </div>
  );
}
