import { createApi } from "@reduxjs/toolkit/query/react";
import { baseQuery } from "@/lib/baseQuery";
import type { InvoiceStatus, PaymentMethod, TicketStatus } from "@hassad/shared";

// ── Invoice types ────────────────────────────────────────────────────────────

export interface InvoiceClient {
  id: string;
  companyName: string;
}

export interface Invoice {
  id: string;
  clientId: string;
  contractId?: string | null;
  createdBy: string;
  invoiceNumber: string;
  amount: number;
  status: InvoiceStatus;
  paymentMethod: PaymentMethod;
  issueDate: string;
  dueDate: string;
  paidAt?: string | null;
  sentAt?: string | null;
  paymentReference?: string | null;
  notes?: string | null;
  createdAt: string;
  updatedAt: string;
  client?: InvoiceClient;
}

export interface PaginatedInvoices {
  items: Invoice[];
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

export interface InvoiceFilters {
  status?: InvoiceStatus;
  clientId?: string;
  page?: number;
  limit?: number;
}

export interface CreateInvoiceInput {
  clientId: string;
  contractId?: string;
  amount: number;
  paymentMethod: PaymentMethod;
  issueDate: string;
  dueDate: string;
  notes?: string;
  // invoiceNumber is auto-generated by the server
}

// ── Payment Ticket types ─────────────────────────────────────────────────────

/** Matches DB `PaymentTicket` model — no amount or description fields */
export interface PaymentTicket {
  id: string;
  invoiceId: string;
  clientId: string;
  assignedTo?: string | null;
  status: TicketStatus;
  notes?: string | null;
  createdAt: string;
  resolvedAt?: string | null;
}

export interface PaginatedTickets {
  items: PaymentTicket[];
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

export interface TicketFilters {
  status?: TicketStatus;
  page?: number;
  limit?: number;
}

/** invoiceId is required; amount/description are not in the DB schema */
export interface CreatePaymentTicketInput {
  invoiceId: string;
  clientId: string;
  assignedTo?: string;
  notes?: string;
}

// ── API slice ─────────────────────────────────────────────────────────────────

export const financeApi = createApi({
  reducerPath: "financeApi",
  baseQuery,
  tagTypes: ["Invoice", "PaymentTicket"],
  endpoints: (builder) => ({
    // Invoices
    getInvoices: builder.query<PaginatedInvoices, InvoiceFilters>({
      query: (filters = {}) => ({ url: "/invoices", params: filters }),
      providesTags: (result) =>
        result
          ? [...result.items.map(({ id }) => ({ type: "Invoice" as const, id })), { type: "Invoice", id: "LIST" }]
          : [{ type: "Invoice", id: "LIST" }],
    }),
    getInvoiceById: builder.query<Invoice, string>({
      query: (id) => `/invoices/${id}`,
      providesTags: (_r, _e, id) => [{ type: "Invoice", id }],
    }),
    getInvoicesByClient: builder.query<Invoice[], string>({
      query: (clientId) => `/invoices/by-client/${clientId}`,
      providesTags: (_r, _e, clientId) => [{ type: "Invoice", id: `CLIENT_${clientId}` }],
    }),
    markInvoicePaid: builder.mutation<Invoice, { id: string; paymentReference: string }>({
      query: ({ id, paymentReference }) => ({ url: `/invoices/${id}/mark-paid`, method: "POST", body: { paymentReference } }),
      invalidatesTags: (_r, _e, { id }) => [{ type: "Invoice", id }, { type: "Invoice", id: "LIST" }],
    }),
    sendInvoice: builder.mutation<Invoice, string>({
      query: (id) => ({ url: `/invoices/${id}/send`, method: "POST" }),
      invalidatesTags: (_r, _e, id) => [{ type: "Invoice", id }, { type: "Invoice", id: "LIST" }],
    }),
    createInvoice: builder.mutation<Invoice, CreateInvoiceInput>({
      query: (body) => ({ url: "/invoices", method: "POST", body }),
      invalidatesTags: [{ type: "Invoice", id: "LIST" }],
    }),

    // Payment Tickets
    getPaymentTickets: builder.query<PaginatedTickets, TicketFilters>({
      query: (filters = {}) => ({ url: "/payment-tickets", params: filters }),
      providesTags: (result) =>
        result
          ? [...result.items.map(({ id }) => ({ type: "PaymentTicket" as const, id })), { type: "PaymentTicket", id: "LIST" }]
          : [{ type: "PaymentTicket", id: "LIST" }],
    }),
    getPaymentTicketById: builder.query<PaymentTicket, string>({
      query: (id) => `/payment-tickets/${id}`,
      providesTags: (_r, _e, id) => [{ type: "PaymentTicket", id }],
    }),
    createPaymentTicket: builder.mutation<PaymentTicket, CreatePaymentTicketInput>({
      query: (body) => ({ url: "/payment-tickets", method: "POST", body }),
      invalidatesTags: [{ type: "PaymentTicket", id: "LIST" }],
    }),
    resolvePaymentTicket: builder.mutation<PaymentTicket, string>({
      query: (id) => ({ url: `/payment-tickets/${id}/resolve`, method: "POST" }),
      invalidatesTags: (_r, _e, id) => [{ type: "PaymentTicket", id }, { type: "PaymentTicket", id: "LIST" }],
    }),
  }),
});

export const {
  useGetInvoicesQuery,
  useGetInvoiceByIdQuery,
  useGetInvoicesByClientQuery,
  useMarkInvoicePaidMutation,
  useSendInvoiceMutation,
  useCreateInvoiceMutation,
  useGetPaymentTicketsQuery,
  useGetPaymentTicketByIdQuery,
  useCreatePaymentTicketMutation,
  useResolvePaymentTicketMutation,
} = financeApi;
